---
title: "Staton Road"
output:
  html_document:
    df_print: paged
---

Meter readings for gas, water and electricity consumption & production figures.

```{r message=FALSE, warning=FALSE, include=FALSE}
library(data.table)
library(ggplot2)
library(lubridate)

########################################################
# analyse meter readings over time & season
# data can be from local file or from google docs sheet
########################################################

data.source <- list(local = "meter.readings.csv",
                    g.doc =  "1YSv-EKJq7lm0wUCAOsnJ9y7OCkmaF2-gNEx6crz9diA"
                    )

use.source <- "g.doc"

# the data source has n rows of data and a header row with the names
# date, water, gas, made, bought, sold, people, notes
# date  date of reading.
# water reading from water meter. reset when new meter installed.
# gas   reading from gas meter.
# made  Etotal reading from solar power inverter.
# bought  power read from meter (electricity from network to house).
# sold  ALT1 reading from meter (electricity from house to network).
# people  (roughly) the number of people staying in the house over the period.
# notes any additional text notes about the weather, faults etc.
```


```{r}
#
if (use.source == "g.doc") {
  # Google Sheets version
  readings <- googlesheets4::read_sheet(data.source[[use.source]])
  meter.readings <- as.data.table(readings)
} else {
  meter.readings <- fread(data.source[[use.source]], showProgress = FALSE)
}


## GS4 gets the dates right so no need for this
# fix any odd date formats.
# google docs occasionally gives two digit years, but always in d m y order for my data
# meter.readings$date <-as.Date(parse_date_time(x = meter.readings$date, 
#                                              orders = c("d m y")), tz = "UTC")

# work out how much we actually used (we sell some of what we make and use all that we buy)
meter.readings[, used := (made - sold)+ bought]

# find where the new water meter was installed (read on day before change then at the end of the next week)
change <- meter.readings[, which(shift(water) > water)]
# so the last reading before the change needs to be added to all subsequent readings to get the cumulative reading
last.old <- meter.readings[change-1, water]
meter.readings[, water := c(water[1:change-1], water[change:.N] + last.old)]
```

Most recent readings were:
```{r}
print(last(meter.readings))
```

```{r}
# calculate the incremental change (the difference from previous reading)
measure.cols <- c("water", "gas", "made", "bought", "sold", "used")
daily <- meter.readings[, lapply(.SD, diff), .SDcols = measure.cols]

# water meter changed on 2018-06-19, starts again from 0000
# look for discontinuity in diff() values and substitute 
# the actual amount (which is the diff from zero)
daily[water < 0, water := meter.readings[c(FALSE, diff(water) < 0), water] ]

# work out how many days between readings
daily[, span := as.integer(diff(meter.readings$date))]
# divide change by number of days to calcluate the daily increment
daily[, (measure.cols) := lapply(.SD, "/", span), .SDcols = measure.cols]

# add back the date of the reading, the number of people in the house
# for that week and any notes
# drop the first row so that they line up with the diff'ed readings
info.cols <- c("date", "people", "notes")
daily[, (info.cols) := meter.readings[, tail(.SD, -1), .SDcols = info.cols]]

# add month and year variables for later ease
daily[, c("year", "month") := list(year(date), month(date))]

# censor the water consumption for known problems
daily[date == "2013-04-13", water := NA] # had a leak
daily[date == "2010-11-07", water := NA] # broken tap timer
daily[date == "2017-12-23", water := NA] # tap left on trees overnight

# quantities that make sense to plot monthly put into long format for plotting
daily.l <- melt(daily, id.vars = "date", measure.vars = measure.cols)
# add month & year for plotting
daily.l[, c("year", "month") := list(year(date), month(date))]
```
```{r plot_all, echo=FALSE, message=FALSE, warning=FALSE}
# plot the measured quantities (i.e.not span or number of people or notes) monthly
# reorder the variables to get the plot we want: 
# consumption in top row, power made, in & out electricity in the bottom row
daily.l[, variable:= factor(variable, 
                            levels = c("water", "gas", "used", 
                                       "made", "sold", "bought"))
        ]
```
```{r plot_readings, echo=FALSE, message=FALSE, warning=FALSE, out.width = "100%"}
# plot all the data just over time
raw <- ggplot(daily.l) + 
                aes(x = date, y = value) + 
                geom_line(colour = "grey") + geom_point() + 
                facet_wrap(~variable, scales = "free") +
                labs(title = "weekly readings", x = "time", y = "value per day")
print(raw)
```
```{r plot_seasonal, echo=FALSE, message=FALSE, warning=FALSE, out.width="100%"}
# plot by month to show the seasonal variation
seasonal <- ggplot(daily.l) + 
                  aes(x = month(date, label = TRUE, abbr = TRUE), 
                      y = value, 
                      colour = year) + 
                  geom_point() + geom_smooth(aes(x = month(date)), span = 0.4) +
                  facet_wrap(~variable, scales = "free") + 
                  labs(title = "seasonal variation", x = "month", y = "value")
print(seasonal)
```
```{r plot_trends, echo=FALSE, message=FALSE, warning=FALSE}
# calculate monthly averages to stabilise the variance a bit
# average date to put average measurement at reasonable mid point for each month
monthly.l <- daily.l[, .(monthly = mean(value, na.rm = TRUE), 
                         date = mean(date)), 
                     by = "variable,month,year"]

# to get the anomaly we need the average by month across all years
# na.rm because we have some missing data (particularly pre-solar power figures)
monthly.means <- monthly.l[, .(mean = mean(monthly, na.rm = TRUE)),
                           by = "variable,month"]
```
```{r message=FALSE, warning=FALSE, out.width="100%"}
# anomaly is each monthly average - the average for that month over the whole data set
# use a right join to bring in the matching monthly mean data for each variable
anomaly.l <- monthly.l[monthly.means, .(variable, 
                                        year, month, date, 
                                        monthly, 
                                        mean = mean, 
                                        anomaly = monthly - mean),
                       on = c("variable", "month"), ]

trends <- ggplot(anomaly.l[variable %in% c("water", "gas", "made", "used"),]) + 
                  aes(x=date, y=anomaly) + 
                  geom_point() + geom_smooth() +
                  facet_wrap(~variable, scales="free") + 
                  labs(title="long term trends", x = "year", y = "anomaly")
print(trends)
```